apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    name: ''
    namespace: vault
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0
    chart: vault
    helm:
      parameters:
        - name: ui.enabled
          value: 'true'
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
